#!/bin/bash
# Quick deployment checklist for newdaylogisticsllc.com

echo "=== NDAY OM Deployment Checklist ==="
echo ""
echo "Prerequisites:"
echo "1. GitHub account (repo must be pushed)"
echo "2. Railway account (https://railway.app)"
echo "3. Vercel account (https://vercel.app)"
echo "4. Access to newdaylogisticsllc.com domain DNS"
echo ""
echo "=== BACKEND DEPLOYMENT (Railway) ==="
echo ""
echo "Step 1: Push to GitHub"
echo "  $ git add -A"
echo "  $ git commit -m 'Ready for production deployment'"
echo "  $ git push origin master"
echo ""
echo "Step 2: Deploy Backend"
echo "  1. Go to https://railway.app"
echo "  2. Click 'New Project' → 'Deploy from GitHub'"
echo "  3. Select your DSP_OM repository"
echo "  4. Click 'Deploy from GitHub'"
echo "  5. Wait for deployment to complete"
echo "  6. Copy the URL from Railway dashboard (https://xxxx.railway.app)"
echo ""
echo "=== FRONTEND DEPLOYMENT (Vercel) ==="
echo ""
echo "Step 3: Deploy Frontend"
echo "  1. Go to https://vercel.app"
echo "  2. Click 'New Project' → 'Import Git Repo'"
echo "  3. Select your DSP_OM repository"
echo "  4. Set Root Directory: 'frontend'"
echo "  5. Add environment variable:"
echo "     - Name: NEXT_PUBLIC_API_URL"
echo "     - Value: https://xxxx.railway.app (from Step 2)"
echo "  6. Click 'Deploy'"
echo "  7. Wait for Vercel deployment complete"
echo "  8. Copy your Vercel URL (https://dsp-om.vercel.app)"
echo ""
echo "=== DOMAIN SETUP ==="
echo ""
echo "Step 4: Point Domain to Vercel"
echo "  1. Go to your domain registrar"
echo "  2. Find DNS settings for newdaylogisticsllc.com"
echo "  3. Add CNAME record:"
echo "     - Name: @ (root)"
echo "     - Value: cname.vercel-dns.com."
echo "  4. Save changes (takes 5-10 minutes)"
echo ""
echo "Step 5: Verify in Vercel"
echo "  1. Go to Vercel dashboard"
echo "  2. Select your project"
echo "  3. Go to Settings → Domains"
echo "  4. Click 'Add Domain'"
echo "  5. Enter: newdaylogisticsllc.com"
echo "  6. Vercel auto-configures SSL (free)"
echo ""
echo "=== TESTING ==="
echo ""
echo "Step 6: Verify Live Site"
echo "  1. Visit https://newdaylogisticsllc.com"
echo "  2. Upload test DOP, Fleet, Cortex, Route Sheets"
echo "  3. Verify PDF generation works"
echo "  4. Check browser console for errors"
echo ""
echo "=== TROUBLESHOOTING ==="
echo ""
echo "Backend not starting:"
echo "  - Check Railway logs for Python errors"
echo "  - Verify Procfile exists in root"
echo "  - Verify requirements.txt has all packages"
echo ""
echo "Frontend can't reach backend:"
echo "  - Verify NEXT_PUBLIC_API_URL in Vercel env vars"
echo "  - Check backend URL is correct (with https://)"
echo "  - Look at Network tab in browser DevTools"
echo ""
echo "=== NEXT STEPS ==="
echo ""
echo "After deployment:"
echo "  1. Monitor Railway dashboard for errors"
echo "  2. Check Vercel analytics for traffic"
echo "  3. Set up email notifications for failures"
echo "  4. (Optional) Add database for historical tracking"
echo "  5. (Optional) Configure auto-scaling on Railway"
echo ""
echo "Questions? See DEPLOYMENT.md for more details"
